version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: order_history_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_history
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_pass
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 